SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Valeur;
TRUNCATE TABLE Type;
TRUNCATE TABLE Categorie;
TRUNCATE TABLE soldeInitial;
TRUNCATE TABLE Droit;
TRUNCATE TABLE Dept;

SET FOREIGN_KEY_CHECKS = 1;
